apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: home-assistant
    server: https://kubernetes.default.svc
  source:
    path: homeAssistant
    repoURL: git@github.com:genrum/argo.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
