apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tanks
spec:
  destination:
    name: in-cluster
    namespace: tanks
    server: ''
  source:
    path: tanks
    repoURL: git@github.com:genrum/argo.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
