apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant.paxel.ca
  namespace: home-assistant
spec:
  secretName: home-assistant.paxel.ca-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: home-assistant.paxel.ca
  dnsNames:
  - home-assistant.paxel.ca