# Ingress Definition for Home Assistant Application
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    # external-dns.alpha. kubernetes. io/hostname: "homeassistant.paxel.ca."
    # external-dns.alpha. kubernetes.io/target: "router.paxel.ca."
spec:
  ingressClassName: nginx
  rules:
    - host: bigfoot.paxel.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant-service
                port:
                  number: 8123                
  tls:
    - hosts:
        - bigfoot.paxel.ca
      secretName: bigfoot.paxel.ca-tls

---
# Namespace Definition
apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
---

# Service Definition for Home Assistant Application
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
  namespace: home-assistant
  labels:
    name: home-assistant
spec:
  selector:
    app: home-assistant
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
  type: LoadBalancer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

# Deployment Definition for Home Assistant Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant-deploy
  namespace: home-assistant
  labels:
    name: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      name: home-assistant
  template:
    metadata:
      labels:
        name: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: homeassistant/home-assistant:stable
          ports:
            - containerPort: 8123
              protocol: TCP
          volumeMounts: 
            - name: home-assistant-config
              mountPath: /config
      volumes: 
        - name: home-assistant-config
          persistentVolumeClaim: 
            claimName: home-assistant-config