apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tanks.paxel.ca
  namespace: tanks-test
spec:
  secretName: tanks.paxel.ca-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: tanks.paxel.ca
  dnsNames:
  - tanks.paxel.ca